//
//  SWSanityTests.m
//  Switch
//
//  Created by Scott Perry on 05/13/16.
//  Copyright © 2016 Scott Perry. All rights reserved.
//

#import "SWWindowListServiceTestSuperclass.h"

@interface SWSanityTests : SWWindowListServiceTestSuperclass

@end

@implementation SWSanityTests

- (void)test1463163574;
{
    // Raw list:
    NSArray *infoList = @[
        @{
            NNWindowLayer : @3000,
            NNWindowAlpha : @0.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @276,
            NNWindowNumber : @722,
            NNWindowOwnerName : @"universalaccessd",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @90,
                @"Width" : @40,
                @"X" : @1310,
                @"Y" : @58,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @5280,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @41791,
            NNWindowNumber : @16565,
            NNWindowOwnerName : @"Switch",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @30,
                @"X" : @1000,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @5280,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @280,
            NNWindowNumber : @12,
            NNWindowOwnerName : @"Little Snitch Agent",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @28,
                @"X" : @947,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @5280,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @636,
            NNWindowNumber : @107,
            NNWindowOwnerName : @"Cloak",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @25,
                @"X" : @975,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1184,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @635,
            NNWindowNumber : @112,
            NNWindowOwnerName : @"Alfred 2",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @0,
                @"Width" : @0,
                @"X" : @1000,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1184,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @58258,
            NNWindowNumber : @8582,
            NNWindowOwnerName : @"CrashPlan menu bar",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @0,
                @"Width" : @0,
                @"X" : @1030,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1184,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @41622,
            NNWindowNumber : @5887,
            NNWindowOwnerName : @"Dropbox",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @0,
                @"Width" : @0,
                @"X" : @1030,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @25760,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @336,
            NNWindowNumber : @33,
            NNWindowOwnerName : @"SystemUIServer",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @230,
                @"X" : @1030,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @5280,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @632,
            NNWindowNumber : @103,
            NNWindowOwnerName : @"Bartender",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @24,
                @"X" : @1260,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @9376,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @343,
            NNWindowNumber : @43,
            NNWindowOwnerName : @"Spotlight",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @36,
                @"X" : @1284,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @25,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @9376,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @336,
            NNWindowNumber : @29,
            NNWindowOwnerName : @"SystemUIServer",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @46,
                @"X" : @1320,
                @"Y" : @0,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowOwnerPID : @197,
            NNWindowOwnerName : @"Window Server",
            NNWindowAlpha : @1.000000,
            NNWindowSharingState : @1,
            NNWindowStoreType : @2,
            NNWindowNumber : @19,
            NNWindowName : @"Menubar",
            NNWindowMemoryUsage : @124064,
            NNWindowBounds : @{
                @"Height" : @22,
                @"Width" : @1366,
                @"X" : @0,
                @"Y" : @0,
            },
            NNWindowLayer : @24,
            NNWindowIsOnscreen : @1,
//            NNWindowBackingLocationVideoMemory : @1,
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @2360480,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @46473,
            NNWindowNumber : @7814,
            NNWindowOwnerName : @"iTerm2",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @647,
                @"X" : @721,
                @"Y" : @23,
            },
            NNWindowName : @"1. ~/C/Switch (fish)",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @314,
            NNWindowNumber : @16272,
            NNWindowOwnerName : @"Safari",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @740,
                @"Width" : @1165,
                @"X" : @145,
                @"Y" : @23,
            },
            NNWindowName : @"man7.org: How much do __builtin_expect(), likely(), and unlikely() improve performance?",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @314,
            NNWindowNumber : @10096,
            NNWindowOwnerName : @"Safari",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1295,
                @"X" : @42,
                @"Y" : @23,
            },
            NNWindowName : @"numist/Switch - Travis CI",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @58213,
            NNWindowNumber : @14164,
            NNWindowOwnerName : @"Finder",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @336,
                @"Width" : @588,
                @"X" : @730,
                @"Y" : @216,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @3036320,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @774,
            NNWindowNumber : @14030,
            NNWindowOwnerName : @"TextMate",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1009,
                @"X" : @61,
                @"Y" : @23,
            },
            NNWindowName : @"untitled (stdin)",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @2360480,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @73779,
            NNWindowNumber : @9616,
            NNWindowOwnerName : @"Activity Monitor",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @737,
                @"Width" : @720,
                @"X" : @1,
                @"Y" : @23,
            },
            NNWindowName : @"Activity Monitor (All Processes)",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @3036320,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @774,
            NNWindowNumber : @9425,
            NNWindowOwnerName : @"TextMate",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1009,
                @"X" : @355,
                @"Y" : @23,
            },
            NNWindowName : @"notes.txt — keyboardio",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @4080800,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @17923,
            NNWindowNumber : @11797,
            NNWindowOwnerName : @"Sublime Text 2",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1366,
                @"X" : @0,
                @"Y" : @23,
            },
            NNWindowName : @"Rakefile — Switch",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @3933344,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @50667,
            NNWindowNumber : @7772,
            NNWindowOwnerName : @"Sublime Text",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1067,
                @"X" : @1,
                @"Y" : @23,
            },
            NNWindowName : @"Makefile — model01_keyscanner_firmware/firmware — keyboardio",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @60716,
            NNWindowNumber : @9484,
            NNWindowOwnerName : @"App Store",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @688,
                @"Width" : @1000,
                @"X" : @14,
                @"Y" : @36,
            },
            NNWindowName : @"",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @50514,
            NNWindowNumber : @7412,
            NNWindowOwnerName : @"Preview",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @702,
                @"Width" : @1330,
                @"X" : @25,
                @"Y" : @34,
            },
            NNWindowName : @"model01-left-hand.pdf (1 page)",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @1024,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @50514,
            NNWindowNumber : @7416,
            NNWindowOwnerName : @"Preview",
            NNWindowStoreType : @1,
            NNWindowBounds : @{
                @"Height" : @702,
                @"Width" : @1330,
                @"X" : @10,
                @"Y" : @57,
            },
            NNWindowName : @"model01-right-hand.pdf (1 page)",
        },
        @{
            NNWindowLayer : @0,
            NNWindowAlpha : @1.000000,
            NNWindowMemoryUsage : @3986592,
            NNWindowIsOnscreen : @1,
            NNWindowSharingState : @1,
            NNWindowOwnerPID : @54478,
            NNWindowNumber : @7980,
            NNWindowOwnerName : @"GitHub Desktop",
            NNWindowStoreType : @2,
            NNWindowBounds : @{
                @"Height" : @741,
                @"Width" : @1341,
                @"X" : @25,
                @"Y" : @23,
            },
            NNWindowName : @"keyboardio/HID",
        },
    ];
    
    /* Sorted window group list:
    {(
      <7814 (1. ~/C/Switch (fish)), 1 windows>,
      <16272 (man7.org: How much do __builtin_expect(), likely(), and unlikely() improve performance?), 1 windows>,
      <10096 (numist/Switch - Travis CI), 1 windows>,
      <14030 (untitled (stdin)), 1 windows>,
      <9616 (Activity Monitor (All Processes)), 1 windows>,
      <9425 (notes.txt — keyboardio), 1 windows>,
      <11797 (Rakefile — Switch), 1 windows>,
      <7772 (Makefile — model01_keyscanner_firmware/firmware — keyboardio), 1 windows>,
      <9484 (App Store), 1 windows>,
      <7412 (model01-left-hand.pdf (1 page)), 1 windows>,
      <7416 (model01-right-hand.pdf (1 page)), 1 windows>,
      <7980 (keyboardio/HID), 1 windows>
    )} */
    [self updateListServiceWithInfoList:infoList];
    
    XCTAssertEqual(self.listService.windows.count, 12, @"");
}

@end
